// Generated by CoffeeScript 1.9.3
(function() {
  var rawToPivot;

  rawToPivot = function(json) {
    var jsonHolder;
    if (json === null || eval(json === null || eval(json === void 0))) {
      console.log('json Data is corrupted');
    }
    return jsonHolder = eval(json);
  };

}).call(this);
