// Generated by CoffeeScript 1.9.3

/* there are no semicolons inb coffee 
 unless is the opposite of if 
 is = === 
 isn't = !== 
 ? checks for null
 */

(function() {
  var axis, changeTheme, data, hiddenAttributes, i, j, sampleData3a, tpl;

  data = [
    {
      color: "blue",
      shape: "circle"
    }, {
      color: "red",
      shape: "triangle"
    }
  ];

  hiddenAttributes = [];

  for (i = j = 1; j <= 200; i = ++j) {
    hiddenAttributes.push('val' + i);
  }

  hiddenAttributes.splice(9, 1);

  tpl = $.pivotUtilities.aggregatorTemplates;

  axis = {
    rows: ["sctin1"],
    cols: ["val10"],
    hiddenAttributes: hiddenAttributes,
    aggregators: {
      'this': function() {
        return tpl.value()();
      }
    }
  };

  sampleData3a = sampleData2['rows'];

  $("#mainTable").pivotUI(sampleData3a, axis);

  $('.click').click(function() {
    return changeTheme(this.value);
  });

  changeTheme = function(num) {
    if (num == null) {
      num = 0;
    }
    return $('#pivotThemes').attr('href', "css/pivotThemes/theme" + num + ".css");
  };


  /*
  
  sum = $.pivotUtilities.aggregatorTemplates.sum
  numberFormat = $.pivotUtilities.numberFormat
  intFormat = numberFormat({digitsAfterDecimal: 0})
  
  $("#output").pivot(
      [
          {color: "blue", shape: "circle", value: 1},
          {color: "red", shape: "triangle", value: 2},
          {color: "blue", shape: "circle", value: 3},
          {color: "red", shape: "triangle", value: 4}
      ],
      {
          rows: ["color"],
          cols: ["shape"],
          aggregator: sum(intFormat)(["value"])
      }
  )
   */

}).call(this);
